/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ir.sain.university.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the University service. Represents a row in the &quot;UNV_University&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ir.sain.university.model.impl.UniversityModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ir.sain.university.model.impl.UniversityImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see University
 * @generated
 */
@ProviderType
public interface UniversityModel
	extends BaseModel<University>, GroupedModel, ShardedModel,
			StagedAuditedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a university model instance should use the {@link University} interface instead.
	 */

	/**
	 * Returns the primary key of this university.
	 *
	 * @return the primary key of this university
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this university.
	 *
	 * @param primaryKey the primary key of this university
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this university.
	 *
	 * @return the uuid of this university
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this university.
	 *
	 * @param uuid the uuid of this university
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the university ID of this university.
	 *
	 * @return the university ID of this university
	 */
	public long getUniversityId();

	/**
	 * Sets the university ID of this university.
	 *
	 * @param universityId the university ID of this university
	 */
	public void setUniversityId(long universityId);

	/**
	 * Returns the group ID of this university.
	 *
	 * @return the group ID of this university
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this university.
	 *
	 * @param groupId the group ID of this university
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this university.
	 *
	 * @return the company ID of this university
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this university.
	 *
	 * @param companyId the company ID of this university
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this university.
	 *
	 * @return the user ID of this university
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this university.
	 *
	 * @param userId the user ID of this university
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this university.
	 *
	 * @return the user uuid of this university
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this university.
	 *
	 * @param userUuid the user uuid of this university
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this university.
	 *
	 * @return the user name of this university
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this university.
	 *
	 * @param userName the user name of this university
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this university.
	 *
	 * @return the create date of this university
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this university.
	 *
	 * @param createDate the create date of this university
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this university.
	 *
	 * @return the modified date of this university
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this university.
	 *
	 * @param modifiedDate the modified date of this university
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this university.
	 *
	 * @return the status of this university
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this university.
	 *
	 * @param status the status of this university
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this university.
	 *
	 * @return the status by user ID of this university
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this university.
	 *
	 * @param statusByUserId the status by user ID of this university
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this university.
	 *
	 * @return the status by user uuid of this university
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this university.
	 *
	 * @param statusByUserUuid the status by user uuid of this university
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this university.
	 *
	 * @return the status by user name of this university
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this university.
	 *
	 * @param statusByUserName the status by user name of this university
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this university.
	 *
	 * @return the status date of this university
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this university.
	 *
	 * @param statusDate the status date of this university
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the name of this university.
	 *
	 * @return the name of this university
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this university.
	 *
	 * @param name the name of this university
	 */
	public void setName(String name);

	/**
	 * Returns <code>true</code> if this university is approved.
	 *
	 * @return <code>true</code> if this university is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this university is denied.
	 *
	 * @return <code>true</code> if this university is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this university is a draft.
	 *
	 * @return <code>true</code> if this university is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this university is expired.
	 *
	 * @return <code>true</code> if this university is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this university is inactive.
	 *
	 * @return <code>true</code> if this university is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this university is incomplete.
	 *
	 * @return <code>true</code> if this university is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this university is pending.
	 *
	 * @return <code>true</code> if this university is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this university is scheduled.
	 *
	 * @return <code>true</code> if this university is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}